### ISSUE TITLE
Game states are not correctly applied on poor networking conditions

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1246]
During long SSS rounds there seem to be issues where PVS kind of breaks for certain player entities, causing them to become invisible or have the container data not get applied so all their entities float under them like regular attached entities.

This *is* accompanied by exceptions on the client but I don't have any examples on hand right now.

**Comment by PJB3005** [comment]
Example:
```
Robust.Client.GameObjects.ComponentStateApplyException: Failed to apply comp state: entity=AKMS (11869, RifleAk), comp=Transform
 ---> System.Collections.Generic.KeyNotFoundException: The given key '11844' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Shared.GameObjects.EntityManager.GetEntity(EntityUid uid) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 122
   at Robust.Shared.GameObjects.Components.Transform.TransformComponent.HandleComponentState(ComponentState curState, ComponentState nextState) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs:line 721
   at Robust.Client.GameObjects.ClientEntityManager.HandleEntityState(IComponentManager compMan, IEntity entity, EntityState curState, EntityState nextState) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 288
   --- End of inner exception stack trace ---

```

Seems child entities aren't getting sent correctly?

Edit: actually this seems to be perhaps related but slightly different?

One that's actually containers:

```
Robust.Client.GameObjects.ComponentStateApplyException: Failed to apply comp state: entity=Lily Gibson (20037, HumanMob_Content), comp=ContainerContainer
 ---> System.Collections.Generic.KeyNotFoundException: The given key '20041' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Shared.GameObjects.EntityManager.GetEntity(EntityUid uid) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 122
   at Robust.Client.GameObjects.Components.Containers.ContainerManagerComponent.HandleComponentState(ComponentState curState, ComponentState nextState) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameObjects/Components/Containers/ContainerManagerComponent.cs:line 145
   at Robust.Client.GameObjects.ClientEntityManager.HandleEntityState(IComponentManager compMan, IEntity entity, EntityState curState, EntityState nextState) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 288
   --- End of inner exception stack trace ---

```

**Comment by PJB3005** [comment]
After discussion on Discord and input from Abraham, it seems a possible cause for this is holes in the applied game states due to a bug in the client game state manager or game state processor.

**Comment by PJB3005** [comment]
Indeed, it's caused by poor networking conditions (and as far as I can tell, extrapolation).
