### ISSUE TITLE
Unhandled exception in MIDI thread

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1247]
```
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AudioSource'.
   at Robust.Client.Graphics.Clyde.Clyde.BufferedAudioSource._checkDisposed() in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs:line 754
   at Robust.Client.Graphics.Clyde.Clyde.BufferedAudioSource.WriteBuffer(Int32 handle, ReadOnlySpan`1 data) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs:line 798
   at Robust.Client.Audio.Midi.MidiRenderer.Render(Int32 length) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Client/Audio/Midi/MidiRenderer.cs:line 426
   at Robust.Client.Audio.Midi.MidiManager.ThreadUpdate() in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Client/Audio/Midi/MidiManager.cs:line 341
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

This causes a hard client crash because the MIDI thread has no exception handling.

**Comment by PJB3005** [comment]
Fixed by #1248
