### ISSUE TITLE
Searching `win` crashes the entity spawn window

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/RobustToolbox#1398]
```
[FATL] unhandled: System.Collections.Generic.KeyNotFoundException: The given key 'Robust.Shared.GameObjects.Components.Transform.SnapGridComponent' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Client.GameObjects.SpriteComponent.DummyIconEntity.GetComponent[T]() in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs:line 1944
   at Content.Client.GameObjects.Components.WindowVisualizer.OnChangeData(AppearanceComponent component) in /home/moony/projects/space-station-14/Content.Client/GameObjects/Components/WindowVisualizer.cs:line 20
   at Robust.Client.GameObjects.SpriteComponent.GetPrototypeTextures(EntityPrototype prototype, IResourceCache resourceCache)+MoveNext() in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs:line 1840
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Robust.Client.UserInterface.CustomControls.EntitySpawnWindow.InsertEntityButton(EntityPrototype prototype, Boolean insertFirst, Int32 index) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/CustomControls/EntitySpawnWindow.cs:line 315
   at Robust.Client.UserInterface.CustomControls.EntitySpawnWindow.UpdateVisiblePrototypes() in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/CustomControls/EntitySpawnWindow.cs:line 286
   at Robust.Client.UserInterface.CustomControls.EntitySpawnWindow.FrameUpdate(FrameEventArgs args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/CustomControls/EntitySpawnWindow.cs:line 386
   at Robust.Client.UserInterface.Control.DoFrameUpdate(FrameEventArgs args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/Control.cs:line 734
   at Robust.Client.UserInterface.Control.DoFrameUpdate(FrameEventArgs args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/Control.cs:line 737
   at Robust.Client.UserInterface.Control.DoFrameUpdate(FrameEventArgs args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/Control.cs:line 737
   at Robust.Client.UserInterface.UserInterfaceManager.FrameUpdate(FrameEventArgs args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 184
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/GameController.cs:line 294
   at Robust.Client.GameController.<MainLoop>b__65_3(Object sender, FrameEventArgs args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 108
   at Robust.Shared.Timing.GameLoop.Run() in /home/moony/projects/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 242
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 113
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 59
   at Robust.Client.GameController.Start(String[] args, Boolean contentStart) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 35
   at Robust.Client.GameController.Main(String[] args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 21
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'Robust.Shared.GameObjects.Components.Transform.SnapGridComponent' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Client.GameObjects.SpriteComponent.DummyIconEntity.GetComponent[T]() in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs:line 1944
   at Content.Client.GameObjects.Components.WindowVisualizer.OnChangeData(AppearanceComponent component) in /home/moony/projects/space-station-14/Content.Client/GameObjects/Components/WindowVisualizer.cs:line 20
   at Robust.Client.GameObjects.SpriteComponent.GetPrototypeTextures(EntityPrototype prototype, IResourceCache resourceCache)+MoveNext() in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs:line 1840
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Robust.Client.UserInterface.CustomControls.EntitySpawnWindow.InsertEntityButton(EntityPrototype prototype, Boolean insertFirst, Int32 index) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/CustomControls/EntitySpawnWindow.cs:line 315
   at Robust.Client.UserInterface.CustomControls.EntitySpawnWindow.UpdateVisiblePrototypes() in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/CustomControls/EntitySpawnWindow.cs:line 286
   at Robust.Client.UserInterface.CustomControls.EntitySpawnWindow.FrameUpdate(FrameEventArgs args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/CustomControls/EntitySpawnWindow.cs:line 386
   at Robust.Client.UserInterface.Control.DoFrameUpdate(FrameEventArgs args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/Control.cs:line 734
   at Robust.Client.UserInterface.Control.DoFrameUpdate(FrameEventArgs args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/Control.cs:line 737
   at Robust.Client.UserInterface.Control.DoFrameUpdate(FrameEventArgs args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/Control.cs:line 737
   at Robust.Client.UserInterface.UserInterfaceManager.FrameUpdate(FrameEventArgs args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 184
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/GameController.cs:line 294
   at Robust.Client.GameController.<MainLoop>b__65_3(Object sender, FrameEventArgs args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 108
   at Robust.Shared.Timing.GameLoop.Run() in /home/moony/projects/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 242
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 113
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 59
   at Robust.Client.GameController.Start(String[] args, Boolean contentStart) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 35
   at Robust.Client.GameController.Main(String[] args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 21
```

**Comment by RemieRichards** [comment]
not a toolbox issue, window visualiser in content is the problem.

**Comment by RemieRichards** [comment]
@brndd need to convert your `GetComponent`s to `TryGetComponent`s.

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/space-station-14/pull/2515

**Comment by PJB3005** [comment]
It would be nice if there was a try catch for this though.
