### ISSUE TITLE
Tests randomly fail due to GetSessionByChannel

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1426]
You can observe this on random prs.

```
Failed Test [10 s]
  Error Message:
   System.Collections.Generic.KeyNotFoundException : The given key '81edffba-939e-486d-9a84-a7c923a359be' was not present in the dictionary.
  Stack Trace:
     at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Server.Player.PlayerManager.GetSessionByChannel(INetChannel channel) in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.Server\Player\PlayerManager.cs:line 156
   at Robust.Server.Player.PlayerManager.Robust.Server.Interfaces.Player.IPlayerManager.GetSessionByChannel(INetChannel channel) in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.Server\Player\PlayerManager.cs:line 122
   at Robust.Server.GameObjects.ServerEntityNetworkManager.DispatchEntityNetworkMessage(MsgEntity message) in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityNetworkManager.cs:line 142
   at Robust.Server.GameObjects.ServerEntityNetworkManager.Update() in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityNetworkManager.cs:line 57
   at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime, Histogram histogram) in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 107
   at Robust.Server.GameObjects.ServerEntityManager.Update(Single frameTime, Histogram histogram) in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 966
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 579
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationGameLoop.Run() in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.UnitTesting\RobustIntegrationTest.cs:line 521
   at Robust.Server.BaseServer.MainLoop() in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 400
   at Robust.UnitTesting.RobustIntegrationTest.ServerIntegrationInstance._serverMain() in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.UnitTesting\RobustIntegrationTest.cs:line 381
--- End of stack trace from previous location ---
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationInstance.WaitIdleAsync(Boolean throwOnUnhandled, CancellationToken cancellationToken) in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.UnitTesting\RobustIntegrationTest.cs:line 225
   at Content.IntegrationTests.Tests.Networking.ReconnectTest.Test() in D:\a\space-station-14\space-station-14\Content.IntegrationTests\Tests\Networking\ReconnectTest.cs:line 44
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
```

**Comment by metalgearsloth** [comment]
Also it's not windows only:

https://github.com/space-wizards/space-station-14/pull/2680/checks?check_run_id=1488741920

**Comment by PJB3005** [comment]
Probably fixed by 8357940ef6449f692e825e8d8f8db9cbf8ab10d4

**Comment by PJB3005** [comment]
Nevermind that didn't fix it.

**Comment by metalgearsloth** [comment]
Probably fixed by https://github.com/space-wizards/space-station-14/pull/2728
