### ISSUE TITLE
Unreliable collection concurrent update exceptions when creating entities

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/RobustToolbox#1457]
Happens only sometimes, and mostly in tests.

```
Robust.Shared.GameObjects.EntityCreationException : Exception inside CreateEntity with prototype AirlockServiceGlassLocked
  ----> System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at Robust.Shared.GameObjects.EntityManager.CreateEntity(String prototypeName, Nullable`1 uid) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 325
   at Robust.Client.GameObjects.ClientEntityManager.ApplyEntityStates(EntityState[] curEntStates, IEnumerable`1 deletions, EntityState[] nextEntStates) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameObjects\ClientEntityManager.cs:line 67
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 381
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 208
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController.cs:line 277
   at Robust.Client.GameController.<MainLoop>b__66_0(Object sender, FrameEventArgs args) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 85
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationGameLoop.Run() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.UnitTesting\RobustIntegrationTest.cs:line 521
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 114
   at Robust.UnitTesting.RobustIntegrationTest.ClientIntegrationInstance._clientMain() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.UnitTesting\RobustIntegrationTest.cs:line 456
--- End of stack trace from previous location ---
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationInstance.WaitIdleAsync(Boolean throwOnUnhandled, CancellationToken cancellationToken) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.UnitTesting\RobustIntegrationTest.cs:line 203
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationInstance.WaitRunTicks(Int32 ticks) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.UnitTesting\RobustIntegrationTest.cs:line 245
   at Content.IntegrationTests.ContentIntegrationTest.RunTicksSync(ClientIntegrationInstance client, ServerIntegrationInstance server, Int32 ticks) in E:\Projects\C#\space-station-14\Content.IntegrationTests\ContentIntegrationTest.cs:line 196
   at Content.IntegrationTests.ContentIntegrationTest.StartConnectedPairShared(ClientIntegrationInstance client, ServerIntegrationInstance server) in E:\Projects\C#\space-station-14\Content.IntegrationTests\ContentIntegrationTest.cs:line 184
   at Content.IntegrationTests.ContentIntegrationTest.StartConnectedServerClientPair(ClientIntegrationOptions clientOptions, ServerIntegrationOptions serverOptions) in E:\Projects\C#\space-station-14\Content.IntegrationTests\ContentIntegrationTest.cs:line 106
   at Content.IntegrationTests.Tests.Damage.DamageVisualizerTest.DamageVisualizerTwoStatesTest() in E:\Projects\C#\space-station-14\Content.IntegrationTests\Tests\Damage\DamageVisualizerTest.cs:line 111
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaitable)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
--InvalidOperationException
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Robust.Shared.Reflection.ReflectionManager.TryLooseGetType(String name, Type& type) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Reflection\ReflectionManager.cs:line 149
   at Robust.Shared.Reflection.ReflectionManager.LooseGetType(String name) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Reflection\ReflectionManager.cs:line 129
   at Robust.Client.GameObjects.AppearanceComponent.VisualizerTypeSerializer.NodeToType(Type type, YamlNode node, YamlObjectSerializer serializer) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\Appearance\AppearanceComponent.cs:line 168
   at Robust.Shared.Serialization.YamlObjectSerializer.NodeToType(Type type, YamlNode node) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Serialization\YamlObjectSerializer.cs:line 557
   at Robust.Shared.Serialization.YamlObjectSerializer.NodeToType(Type type, YamlNode node) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Serialization\YamlObjectSerializer.cs:line 508
   at Robust.Shared.Serialization.YamlCustomFormatSerializer`1.NodeToType(Type _type, YamlNode node, YamlObjectSerializer serializer) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Serialization\YamlCustomFormatSerializer.cs:line 27
   at Robust.Shared.Serialization.YamlObjectSerializer.DataField[T](T& value, String name, T defaultValue, WithFormat`1 format, Boolean alwaysWrite) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Serialization\YamlObjectSerializer.cs:line 135
   at Robust.Shared.Serialization.ObjectSerializer.DataField[T](T& value, String name, T defaultValue, Boolean alwaysWrite) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Serialization\ObjectSerializer.cs:line 70
   at Robust.Client.GameObjects.AppearanceComponent.ExposeData(ObjectSerializer serializer) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\Appearance\AppearanceComponent.cs:line 122
   at Robust.Shared.GameObjects.EntityPrototype.EnsureCompExistsAndDeserialize(Entity entity, IComponentFactory factory, String compName, ObjectSerializer ser) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Prototypes\EntityPrototype.cs:line 487
   at Robust.Shared.GameObjects.EntityPrototype.LoadEntity(EntityPrototype prototype, Entity entity, IComponentFactory factory, IEntityLoadContext context) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Prototypes\EntityPrototype.cs:line 451
   at Robust.Shared.GameObjects.EntityManager.CreateEntity(String prototypeName, Nullable`1 uid) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 317
```

**Comment by Acruid** [comment]
Check to see if the test using RobustUnitTesting also has the [Parallelizable] attribute on the class.

**Comment by Acruid** [comment]
Without more info or a way to reproduce this, it is impossible to fix. I'm going to close this, feel free to open it again if needed.

There were multiple threads accessing the EntityManager, and one of them was writing (the one that threw the error, trying to CreateEntity). If this ever happens again during debugging, you need to look at the threads window and see which threads are inside EntityManager. Then you can inspect the stack and figure out how multiple threads are accessing EntityManager.
https://github.com/dotnet/runtime/issues/26868
