### ISSUE TITLE
Updating to an engine version without a tag causes an undescriptive sandbox exception

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/RobustToolbox#1577]
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Assembly Content.Shared failed type checks.) (Assembly Content.Client failed type checks.)
 ---> Robust.Shared.ContentPack.TypeCheckFailedException: Assembly Content.Shared failed type checks.
   at Robust.Shared.ContentPack.ModLoader.<>c__DisplayClass15_1.<TryLoadModulesFrom>b__1(KeyValuePair`2 pair) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/ContentPack/ModLoader.cs:line 100
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Robust.Shared.ContentPack.ModLoader.TryLoadModulesFrom(ResourcePath mountPath, String filterPrefix) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/ContentPack/ModLoader.cs:line 93
   at Robust.Client.GameController.Startup(Func`1 logHandlerFactory) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController.cs:line 144
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart, IMainArgs loaderArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 53
   at Robust.Client.GameController.Start(String[] args, Boolean contentStart, IMainArgs loaderArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 33
   at Robust.Client.GameController.LoaderEntryPoint.Main(IMainArgs args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Loader.cs:line 14
   at SS14.Loader.Program.Run()
   at SS14.Loader.Program.Main(String[] args)
 ---> (Inner Exception #1) Robust.Shared.ContentPack.TypeCheckFailedException: Assembly Content.Client failed type checks.
   at Robust.Shared.ContentPack.ModLoader.<>c__DisplayClass15_1.<TryLoadModulesFrom>b__1(KeyValuePair`2 pair) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/ContentPack/ModLoader.cs:line 100
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
```

**Comment by PaulRitter** [comment]
so you are saying if you use the system incorrectly it breaks?

**Comment by DrSmugleaf** [comment]
> so you are saying if you use the system incorrectly it breaks?

I am saying that updating the engine to a commit without a tag produces an inappropriately indescriptive error that doesn't helpfully or meaningfully lead the reader to the cause of said error as a product of their newly gained information as would be expected from a diagnostic tool that informs the operator when something has gone wrong, and instead it detracts in their efforts of finding the cause for said problem, misleading the user in the process as showed yesterday with me, Acrid and Zumorica.

So no. Not what I'm saying.
I hope that clears it up.

**Comment by AJCM-git** [comment]
can confirm, the industrial revolution and its consecuences to the human race have been a

**Comment by PJB3005** [comment]
We could make the content build system fail if the engine version tag isn't the exact commit, I guess.

**Comment by DrSmugleaf** [comment]
> We could make the content build system fail if the engine version tag isn't the exact commit, I guess.

Acceptable. Though how to do that beats me.
See also https://github.com/space-wizards/space-station-14/issues/3328

**Comment by PJB3005** [comment]
Seems like `--exact-match` to the `git describe` command used when resolving the engine version, easy.
