### ISSUE TITLE
Reconnecting locally causes a duplicate event bus subscription error

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/RobustToolbox#1655]
Steps to reproduce:
- Start a client and server locally.
- Connect to the server.
- Disconnect.
- Connect again.

This is because EntitySystem.Initialize runs on reconnects, which is where we are putting the subscription calls through SubscribeLocalEvent, and the directed entity event bus subscriptions are not cleared on disconnect.

```
[ERRO] net: [::1]:1212: exception in message handler for MsgPlayerList:
System.InvalidOperationException: Duplicate Subscriptions for comp=SurgeryTargetComponent, event=SurgeryTargetComponentRemovedMessage
   at Robust.Shared.GameObjects.EntityEventBus.EventTables.Subscribe(Type compType, Type eventType, DirectedEventHandler handler) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 134
   at Robust.Shared.GameObjects.EntityEventBus.SubscribeLocalEvent[TComp,TEvent](ComponentEventHandler`2 handler) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 58
   at Robust.Shared.GameObjects.EntitySystem.SubscribeLocalEvent[TComp,TEvent](ComponentEventHandler`2 handler) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystem.cs:line 124
   at Content.Shared.GameObjects.EntitySystems.SharedSurgerySystem.Initialize() in C:\Projects\C#\space-station-14\Content.Shared\GameObjects\EntitySystems\SharedSurgerySystem.cs:line 22
   at Robust.Shared.GameObjects.EntitySystemManager.Initialize() in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 139
   at Robust.Client.GameObjects.ClientEntityManager.Startup() in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameObjects\ClientEntityManager.cs:line 35
   at Robust.Client.BaseClient.OnPlayerJoinedServer(IPlayerSession session) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\BaseClient.cs:line 153
   at Robust.Client.BaseClient.OnLocalStatusChanged(Object obj, StatusEventArgs eventArgs) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\BaseClient.cs:line 208
   at Robust.Client.Player.LocalPlayer.SwitchState(SessionStatus oldStatus, SessionStatus newStatus) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\Player\LocalPlayer.cs:line 132
   at Robust.Client.Player.PlayerManager.UpdatePlayerList(IEnumerable`1 remotePlayers) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\Player\PlayerManager.cs:line 212
   at Robust.Client.Player.PlayerManager.HandlePlayerList(MsgPlayerList msg) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\Player\PlayerManager.cs:line 168
   at Robust.Shared.Network.NetManager.<>c__DisplayClass93_0`1.<RegisterNetMessage>b__0(NetMessage msg) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Network\NetManager.cs:line 907
   at Robust.Shared.Network.NetManager.DispatchNetMessage(NetIncomingMessage msg) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Network\NetManager.cs:line 842
```

**Comment by Acruid** [comment]
Cannot reproduce, assumed to be fixed.

**Comment by DrSmugleaf** [comment]
> Cannot reproduce, assumed to be fixed.

For it to happen a SubscribeLocalEvent<TComp, TEvent> needs to be placed on a client entity system. No entity systems currently do this on latest master, but I can reproduce it happening with engine commit 6cf5fdc5d on two of my branches which use the new events on the client. 

https://github.com/space-wizards/space-station-14/pull/3635 is an example where this happens, ReconnectTest reproduces it reliably.

**Comment by DrSmugleaf** [comment]
Nevermind this happens if you dont remove the subscriptions on system shutdown. EntityManager.Shutdown only calls a Clear on the entities of the event tables, not the subscriptions as a whole.
