### ISSUE TITLE
Container Crash on round restart

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1736]
I can get it consistently by moving around a bit after restartround and the kitchen crashes. Think it's Robust related and not ss14:

stacktrace:
```
Robust.Client.GameObjects.ComponentStateApplyException: Failed to apply comp state: entity=chef's closet (6489, LockerChefFilled), comp=ContainerContainer
 ---> System.Collections.Generic.KeyNotFoundException: The given key '10810' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Shared.GameObjects.EntityManager.GetEntity(EntityUid uid) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 192
   at Robust.Shared.Containers.ContainerManagerComponent.HandleComponentState(ComponentState curState, ComponentState nextState) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\Containers\ContainerManagerComponent.cs:line 125
   at Robust.Client.GameStates.ClientGameStateManager.HandleEntityState(IComponentManager compMan, IEntity entity, EntityState curState, EntityState nextState) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 587
   --- End of inner exception stack trace ---
   at Robust.Client.GameStates.ClientGameStateManager.HandleEntityState(IComponentManager compMan, IEntity entity, EntityState curState, EntityState nextState) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 596
   at Robust.Client.GameStates.ClientGameStateManager.ApplyEntityStates(EntityState[] curEntStates, IEnumerable`1 deletions, EntityState[] nextEntStates) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 462
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 397
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 216
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 351
   at Robust.Client.GameController.<StartupContinue>b__48_0(Object sender, FrameEventArgs args) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 160
   at Robust.Shared.Timing.GameLoop.Run() in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 197
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 131
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 116
   at Robust.Client.GameController.<>c__DisplayClass77_0.<Run>b__0() in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 83
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Acruid** [comment]
An instance of #1827.
