### ISSUE TITLE
B2DynamicTree sometimes throws when calling Clear

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1807]
Mainly noticeable after restarting round. It happens from rendertree so it is possible its rendertree's fault when calling Clear.

**Comment by PJB3005** [comment]
Do you have a more specific stack trace?

**Comment by metalgearsloth** [comment]
It doesn't want to replicate again so I can check if it's the free proxy but this is what it was:

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Robust.Shared.Physics.B2DynamicTree`1.DestroyProxy(Proxy proxy) in E:\Programming\space-station-14\RobustToolbox\Robust.Shared\Physics\B2DynamicTree.cs:line 295
   at Robust.Shared.Physics.DynamicTree`1.Clear() in E:\Programming\space-station-14\RobustToolbox\Robust.Shared\Physics\DynamicTree.cs:line 107
   at Robust.Client.GameObjects.RenderingTreeSystem.MapManagerOnMapDestroyed(Object sender, MapEventArgs e) in E:\Programming\space-station-14\RobustToolbox\Robust.Client\GameObjects\EntitySystems\RenderingTreeSystem.cs:line 207
   at Robust.Shared.Map.MapManager.DeleteMap(MapId mapID) in E:\Programming\space-station-14\RobustToolbox\Robust.Shared\Map\MapManager.cs:line 205
   at Robust.Client.Map.ClientMapManager.ApplyGameStatePost(GameStateMapData data) in E:\Programming\space-station-14\RobustToolbox\Robust.Client\Map\ClientMapManager.cs:line 225
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in E:\Programming\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 401
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in E:\Programming\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 217
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in E:\Programming\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 372
   at Robust.Client.GameController.<StartupContinue>b__48_0(Object sender, FrameEventArgs args) in E:\Programming\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 159
   at Robust.Shared.Timing.GameLoop.Run() in E:\Programming\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 197
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in E:\Programming\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 131
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in E:\Programming\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 116
   at Robust.Client.GameController.<>c__DisplayClass77_0.<Run>b__0() in E:\Programming\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 83
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Skysub** [comment]
I have been experiencing the same problem, and i can recreate it. I forked the repository two days ago and got set up. I press start in visual studio, join the server. Walk around a little bit, and then restart the round using the admin tools. This causes the problem almost every time. The included screenshot might be of help too. I'm a novice when it comes to opensource development and this codebase. It looks very complicated. Hope this helps. :)
Details:
```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=Robust.Shared
  StackTrace:
   at Robust.Shared.Physics.B2DynamicTree`1.FreeNode(Proxy proxy) in C:\Users\tilfa\source\openSource\space-station-14\RobustToolbox\Robust.Shared\Physics\B2DynamicTree.cs:line 254
   at Robust.Shared.Physics.B2DynamicTree`1.DestroyProxy(Proxy proxy) in C:\Users\tilfa\source\openSource\space-station-14\RobustToolbox\Robust.Shared\Physics\B2DynamicTree.cs:line 295
   at Robust.Shared.Physics.DynamicTree1.Clear() in C:\Users\tilfa\source\openSource\space-station-14\RobustToolbox\Robust.Shared\Physics\DynamicTree.cs:line 107
   at Robust.Client.GameObjects.RenderingTreeSystem.MapManagerOnMapDestroyed(Object sender, MapEventArgs e) in C:\Users\tilfa\source\openSource\space-station-14\RobustToolbox\Robust.Client\GameObjects\EntitySystems\RenderingTreeSystem.cs:line 242
   at Robust.Shared.Map.MapManager.DeleteMap(MapId mapID) in C:\Users\tilfa\source\openSource\space-station-14\RobustToolbox\Robust.Shared\Map\MapManager.cs:line 205
   at Robust.Client.Map.ClientMapManager.ApplyGameStatePost(GameStateMapData data) in C:\Users\tilfa\source\openSource\space-station-14\RobustToolbox\Robust.Client\Map\ClientMapManager.cs:line 225
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in C:\Users\tilfa\source\openSource\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 401
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in C:\Users\tilfa\source\openSource\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 217
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in C:\Users\tilfa\source\openSource\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 372
   at Robust.Client.GameController.<StartupContinue>b__48_0(Object sender, FrameEventArgs args) in C:\Users\tilfa\source\openSource\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 159
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\tilfa\source\openSource\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 197
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in C:\Users\tilfa\source\openSource\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 131
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in C:\Users\tilfa\source\openSource\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 116
   at Robust.Client.GameController.<>c__DisplayClass77_0.<Run>b__0() in C:\Users\tilfa\source\openSource\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 83
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

Screenshot:
![screenshot](https://user-images.githubusercontent.com/78206776/121195244-bb0c4280-c86f-11eb-801b-e37b045600ca.png)

**Comment by metalgearsloth** [comment]
Given we have purged NaNs this shouldn't happen anymore.
