### ISSUE TITLE
Containers expect child entitites to exist on the client

### ISSUE THREAD

**Issue by Acruid** [space-wizards/RobustToolbox#1827]
## Example of the error
```
[ERRO] runtime: Caught exception in "Component state apply"
Robust.Client.GameObjects.ComponentStateApplyException: Failed to apply comp state: entity=communications computer (30819, ComputerComms), comp=ContainerContainer
 ---> System.Collections.Generic.KeyNotFoundException: The given key '35245' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Shared.GameObjects.EntityManager.GetEntity(EntityUid uid) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 209
   at Robust.Shared.Containers.ContainerManagerComponent.HandleComponentState(ComponentState curState, ComponentState nextState) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Containers/ContainerManagerComponent.cs:line 122
   at Robust.Client.GameStates.ClientGameStateManager.HandleEntityState(IComponentManager compMan, IEntity entity, EntityEventBus bus, EntityState curState, EntityState nextState) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 594
   --- End of inner exception stack trace ---
```
## Cause
The ContainerManagerComponent client networking blindly assumes that all of it's child entities exist. The server PVS networking does not ensure this, so there can be cases where BVH queries can return the parent container without it's children.

## Reproduction
The root cause of this is because the BVH query for the client's PVS is inaccurate, and there can be instances where all of the entities in the exact same position are not returned. This is basically up to chance (based on the inflated AABB of each entity inside the BVH), and extremely difficult do reproduce live. This should be able to be deterministically reproduced locally. To easily reproduce locally without relying on BVH implementation, manually move the contents of a container through VV far away and outside of the client PVS on the server. When the container enters PVS, this bug should be triggered.

## Resolution
The best solution is to change the container manager logic so that it does not require the contained entities to actually exist in order to work. This solution will also support the proposal of hiding container contents #1432 for increased network performance and cheating reasons.

Another option is ensuring that child entities are always sent with parents in the server PVS system, but unless you can do that without further increasing the perf impact of server networking, this isn't viable.

**Comment by metalgearsloth** [comment]
@ShadowCommander this is done right?

**Comment by ShadowCommander** [comment]
Yes, we now have the second solution, sending all child entities.
