### ISSUE TITLE
Exception trying to connect to a server locally

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#2252]
I have the autoconnect setup for my run config but not sure if it was relevant. Steps to replicate (at least for me):
1. Run joint config
2. Press connect on client before server has finished setting up a round
3. Can't connect, and if you mash the button you get an exception.

This is what you get every time you press "Direct Connect"

```
[DEBG] net: "[::1]:55545": Status changed to Connected, reason: "Connected to A18EEE190B93A3DC"
[INFO] net: "::": "Initiated average roundtrip time to 2.94 ms Remote time is: 23.850689525878906"
[INFO] net: Approved "[::1]:55545" with username "localhost@JoeGenero" user ID "cd1db9f9-4987-49ce-8bc9-4b48ba4aee4e" into the server
[INFO] net: Sending message name string table to ::1.
[DEBG] net: "127.0.0.1:55546": Status changed to Connected, reason: "Connected to 2E4850F243BE1B90"
[INFO] net: "0.0.0.0": "Initiated average roundtrip time to 2.93 ms Remote time is: 23.850686975878908"
[DEBG] net: "127.0.0.1:55546": Status changed to Disconnected, reason: "First connection attempt won."
[INFO] net: Peer 2E4850F243BE1B90 disconnected while handshake was in-progress.
[DEBG] net: "[::1]:55545": Status changed to Disconnected, reason: "Got NetMessage with invalid ID"
[INFO] net: "[::1]:55545": Disconnected ("Got NetMessage with invalid ID")
[DEBG] szr: Cancelling handshake for disconnected client cd1db9f9-4987-49ce-8bc9-4b48ba4aee4e
```

This is the one you get if you spam (there was a whole bunch of task wrapping around it so I didn't copy the whole thing).
```
at System.Threading.Tasks.Task`1.get_Result()
   at Robust.Shared.Network.NetManager.CCHappyEyeballs(Int32 port, IPAddress first, IPAddress second, CancellationToken mainCancelToken) in C:\Programming\Repos\space-station-14\RobustToolbox\Robust.Shared\Network\NetManager.ClientConnect.cs:line 370
```

Expected result: Can actually connect to the game

**Comment by moonheart08** [comment]
This is also an issue sometimes when trying to reconnect to our gameservers (same error)

**Comment by PJB3005** [comment]
Can confirm this appears to happen if you try to reconnect to the game.

**Comment by Acruid** [comment]
Related to https://github.com/space-wizards/RobustToolbox/issues/2443 I think.
