### ISSUE TITLE
Prototype reloading is broken.

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/RobustToolbox#2682]
Editing prototypes in a yaml file (e.g., the beakers in chemistry.yml) results in an error. At a guess, it has to do with the changes to how abstract prototypes work, and maybe its supposed to be filtering out abstract entities when doing the on-prototypes-reloaded invoke? @PaulRitter 

```
[FATL] unhandled: System.Collections.Generic.KeyNotFoundException: The given key 'BaseBeaker' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Shared.Prototypes.PrototypeManager.<>c__DisplayClass22_0.<ReloadPrototypes>b__3(String a) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\Prototypes\PrototypeManager.cs:line 364
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Robust.Shared.Prototypes.PrototypeManager.<ReloadPrototypes>b__22_1(KeyValuePair`2 g) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\Prototypes\PrototypeManager.cs:line 363
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Robust.Shared.Prototypes.PrototypeManager.ReloadPrototypes(Dictionary`2 prototypes) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\Prototypes\PrototypeManager.cs:line 358
   at Robust.Shared.Prototypes.PrototypeManager.ReloadPrototypes(IEnumerable`1 filePaths) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\Prototypes\PrototypeManager.cs:line 314
   at Robust.Client.Prototypes.ClientPrototypeManager.ReloadPrototypeQueue() in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Client\Prototypes\ClientPrototypeManager.cs:line 64
```

**Comment by PaulRitter** [comment]
should be fixed in 956be749b62df00e659f69b372dd2df944993472
