### ISSUE TITLE
'Sticky shoes' physics exception

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/RobustToolbox#2915]
```
System.Collections.Generic.KeyNotFoundException: Entity 579690 does not have a component of type Robust.Shared.GameObjects.TransformComponent
   at Robust.Shared.Physics.SharedBroadphaseSystem.Synchronize(Fixture fixture, Transform transform1) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Physics/SharedBroadphaseSystem.cs:line 604
   at Robust.Shared.Physics.SharedBroadphaseSystem.SynchronizeFixtures(PhysicsComponent body, Vector2 worldPos, Single worldRot, FixturesComponent manager) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Physics/SharedBroadphaseSystem.cs:line 596
   at Robust.Shared.Physics.SharedBroadphaseSystem.OnMove(EntityUid uid, PhysicsComponent component, MoveEvent& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Physics/SharedBroadphaseSystem.cs:line 546
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass43_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 235
   at Robust.Shared.GameObjects.EntityEventBus.EventTables.<>c__DisplayClass17_0`1.<Subscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 378
   at Robust.Shared.GameObjects.EntityEventBus.EventTables.Dispatch(EntityUid euid, Type eventType, Unit& args, Boolean dispatchByReference) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 452
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 149
   at Robust.Shared.GameObjects.TransformComponent.RunDeferred() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs:line 564
   at Robust.Shared.Physics.Dynamics.SharedPhysicsMapComponent.ProcessQueue() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Physics/Dynamics/SharedPhysicsMapComponent.cs:line 222
   at Robust.Shared.GameObjects.SharedPhysicsSystem.SimulateWorld(Single deltaTime, Boolean prediction) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs:line 322
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 317
 Catcher=entsys Sawmill=runtime
```

server-side errors. this happened about 8 minutes into a round and caused weird movement where people would go in random directions that seemed unrelated to which key they were pressing

seemed to happen after the nukie shuttle started getting piloted? for the record I also had an admin frozen person on the nukie shuttle (that I had to ban for immediately griefing the nukies), so for a repro maybe try admin freezing someone on a shuttle and then moving it? idk

**Comment by mirrorcult** [comment]
was fixed after a round restart

**Comment by metalgearsloth** [comment]
Might be fixed by https://github.com/space-wizards/RobustToolbox/pull/2917
