### ISSUE TITLE
Deleted entity somehow remained in transform child set

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/RobustToolbox#3146]
This error was getting spammed on grafana for some time. AFAICT, this was probably a deleted entity that was somehow still inside of some other entity's list of children, so this error occurred whenever the parent moved.

```
Caught exception in entsys
System.Collections.Generic.KeyNotFoundException: Entity 430309 does not have a component of type Robust.Shared.GameObjects.TransformComponent
   at Robust.Shared.GameObjects.EntityQuery`1.GetComponent(EntityUid uid) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 1192
   at Robust.Server.GameStates.PVSSystem.UpdateEntityRecursive(EntityUid uid, TransformComponent xform, EntityCoordinates coordinates, EntityQuery`1 xformQuery, Boolean mover) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameStates/PVSSystem.cs:line 250
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 321
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 194
   at Robust.Shared.GameObjects.TransformComponent.RunDeferred() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs:line 566
   at Robust.Shared.Physics.Dynamics.SharedPhysicsMapComponent.ProcessQueue() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Physics/Dynamics/SharedPhysicsMapComponent.cs:line 200
   at Robust.Shared.GameObjects.SharedPhysicsSystem.SimulateWorld(Single deltaTime, Boolean prediction) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs:line 346
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 317
 Catcher=entsys Sawmill=runtime
```

**Comment by ElectroJr** [comment]
I think this was fixed? At least I haven't seen it come up in a while.
