### ISSUE TITLE
MIDI broken again

### ISSUE THREAD

**Issue by S1ss3l** [space-wizards/RobustToolbox#3376]
So yea, I can't play nor hear midi. Yes I have libfluidsynth-dev, qsynth, fluidsynth all the synth.
I'm on Pop-OS 22.04 (Ubuntu based distro).
What I tried : 
- Installing libfluidsynth-dev (v2.2.5-1), libfluidsynth3 (v2.2.5-1), qsynth (v0.9.6-1)
- setting GLIBC_TUNABLES=glibc.rtld.dynamic_sort=1 as environment variable
- Downgrading glibc (package is named libc6 for my distro and I couldnt find any version prior to 2.35 still online)
- Doing all of the above on a fresh install (Yes I wanna hear music that badly)
- Praying ancient deities

So all this is happening on Wisard's Den Lizard [US West] server and for some unholy reason, on Wizard's Den Test [EU West 3???] I have absolutely no problem playing or hearing MIDI files.

Here's an extract of what I thought would be relevant of the logs : 

!!!WARNING!!!: glibc 2.35 or higher detected (you have 2.35).
If anything misbehaves (weird native crashes, library load failures), try setting GLIBC_TUNABLES=glibc.rtld.dynamic_sort=1 as environment variable.
This is a severe glibc bug introduced in glibc 2.35. See https://github.com/space-wizards/RobustToolbox/issues/2563 for details
[DEBG] root: Runtime: .NET 6.0.4 pop.22.04-x64
[DEBG] root: OS: Linux 6.0.2-76060002-generic #202210150739~1666289067~22.04~fe0ce53 SMP PREEMPT_DYNAMIC Thu O X64

[...]

[ERRO] midi: Failed to initialize fluidsynth due to exception, disabling MIDI support:
System.DllNotFoundException: Unable to load shared library '/home/sissel/SS14/bin/loader/libfluidsynth.so.2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /home/sissel/SS14/bin/loader/libfluidsynth.so.2: cannot open shared object file: No such file or directory
   at System.Runtime.InteropServices.NativeLibrary.LoadFromPath(String libraryName, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at SS14.Loader.Program.LoadContextOnResolvingUnmanaged(Assembly assembly, String unmanaged) in /home/runner/work/SS14.Launcher/SS14.Launcher/SS14.Loader/Program.cs:line 40
   at System.Runtime.Loader.AssemblyLoadContext.GetResolvedUnmanagedDll(Assembly assembly, String unmanagedDllName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDllUsingEvent(String unmanagedDllName, Assembly assembly, IntPtr gchManagedAssemblyLoadContext)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.TryLoad(String libraryName, Assembly assembly, Nullable`1 searchPath, IntPtr& handle)
   at NFluidsynth.Native.LibFluidsynth.<>c.<.cctor>b__10_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at NFluidsynth.Native.LibFluidsynth.fluid_set_log_function(Int32 severity, LoggerDelegate func, IntPtr data)
   at NFluidsynth.Logger.SetLoggerMethod(LoggerDelegate method)
   at Robust.Client.Audio.Midi.MidiManager.InitializeFluidsynth() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Audio/Midi/MidiManager.cs:line 154
   
Moar logs : 
[client.stdout.log](https://github.com/space-wizards/RobustToolbox/files/9863684/client.stdout.log)
[launcher.log](https://github.com/space-wizards/RobustToolbox/files/9863685/launcher.log)

**Comment by gradientvera** [comment]
You need any fluidsynth version below 2.2

**Comment by S1ss3l** [comment]
My bad should have mentionned it, same problem as glibc, I can't find an older package for my distro. Not sure how building it from source is gonna go but I'll give it a try and report back.

EDIT : Successfully built the 2.18 version and it's still not working. Same error as above

**Comment by S1ss3l** [comment]
Also, I don't even know if it's helpful or not at this point but I still get the error, putting libfluidsynth.so.2 from the built 2.18 version in the required /bin/loader folder did not help.

**Comment by S1ss3l** [comment]
Nevermind it was a symlink and I'm a dumbass. For future reference here's what I did : 

- Build [https://github.com/FluidSynth/fluidsynth](url) from source using this : [https://github.com/FluidSynth/fluidsynth/releases/tag/v2.1.8](url) release
- run the following command from [ss14 folder]/bin/loader : 
- ln -s [fluidsynth folder]/build/src/libfluidsynth.so.2 libfluidsynth.so.2

It should create a symbolic link to libfluidsynth.so.2 and everything should work.
Hope this can help someone in the future and sorry for opening an issue for nothing.

**Comment by alliephante** [comment]
Would it be infeasible to bundle a known working libfluidsynth? If I understand their license properly it supports distribution. This would prevent having to compile it on platforms that don't have the right version available since it must be below v2.2.

**Comment by Slava0135** [comment]
> Nevermind it was a symlink and I'm a dumbass. For future reference here's what I did :
> 
>     * Build [https://github.com/FluidSynth/fluidsynth](url) from source using this : [https://github.com/FluidSynth/fluidsynth/releases/tag/v2.1.8](url) release
> 
>     * run the following command from [ss14 folder]/bin/loader :
> 
>     * ln -s [fluidsynth folder]/build/src/libfluidsynth.so.2 libfluidsynth.so.2
> 
> 
> It should create a symbolic link to libfluidsynth.so.2 and everything should work. Hope this can help someone in the future and sorry for opening an issue for nothing.

Thanks, it worked on Manjaro too.
