### ISSUE TITLE
Client crash after examining

### ISSUE THREAD

**Issue by DamianX** [space-wizards/RobustToolbox#3734]
I've hit this failing debug assertion twice. The second time I had the debugger connected and was trying to reproduce it, it only took a minute or so. I was just walking around the station on a local server examining random things as I moved.

```
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in C:\dev\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 32
   at Robust.Shared.GameObjects.OccluderSystem.ExtractAabb(ComponentTreeEntry`1& entry) in C:\dev\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\OccluderSystem.cs:line 40
   at Robust.Shared.Physics.DynamicTree`1.RayQueryStateCallback[TState](ValueTuple`5& tuple, Proxy proxy, Vector2& hitPos, Single distance) in C:\dev\space-station-14\RobustToolbox\Robust.Shared\Physics\DynamicTree.cs:line 307
   at Robust.Shared.Physics.B2DynamicTree`1.RayCast[TState](TState& state, RayQueryCallback`1 callback, Ray& input) in C:\dev\space-station-14\RobustToolbox\Robust.Shared\Physics\B2DynamicTree.cs:line 980
   at Robust.Shared.Physics.DynamicTree`1.QueryRay[TState](TState& state, RayQueryCallbackDelegate`1 callback, Ray& ray, Boolean approx) in C:\dev\space-station-14\RobustToolbox\Robust.Shared\Physics\DynamicTree.cs:line 281
   at Robust.Shared.ComponentTrees.ComponentTreeSystem`2.IntersectRayWithPredicate[TState](MapId mapId, Ray& ray, Single maxLength, TState state, Func`3 predicate, Boolean returnOnFirstHit) in C:\dev\space-station-14\RobustToolbox\Robust.Shared\ComponentTrees\ComponentTreeSystem.cs:line 296
   at Content.Shared.Examine.ExamineSystemShared.InRangeUnOccluded[TState](MapCoordinates origin, MapCoordinates other, Single range, TState state, Func`3 predicate, Boolean ignoreInsideBlocker, IEntityManager entMan) in C:\dev\space-station-14\Content.Shared\Examine\ExamineSystemShared.cs:line 180
   at Content.Shared.Examine.ExamineSystemShared.InRangeUnOccluded(MapCoordinates origin, MapCoordinates other, Single range, Ignored predicate, Boolean ignoreInsideBlocker, IEntityManager entMan) in C:\dev\space-station-14\Content.Shared\Examine\ExamineSystemShared.cs:line 152
   at Content.Shared.Examine.ExamineSystemShared.CanExamine(EntityUid examiner, MapCoordinates target, Ignored predicate, Nullable`1 examined, ExaminerComponent examinerComp) in C:\dev\space-station-14\Content.Shared\Examine\ExamineSystemShared.cs:line 108
   at Content.Client.Examine.ExamineSystem.CanExamine(EntityUid examiner, MapCoordinates target, Ignored predicate, Nullable`1 examined, ExaminerComponent examinerComp) in C:\dev\space-station-14\Content.Client\Examine\ExamineSystem.cs:line 82
   at Content.Shared.Examine.ExamineSystemShared.CanExamine(EntityUid examiner, EntityUid examined) in C:\dev\space-station-14\Content.Shared\Examine\ExamineSystemShared.cs:line 77
   at Content.Client.Examine.ExamineSystem.Update(Single frameTime) in C:\dev\space-station-14\Content.Client\Examine\ExamineSystem.cs:line 56
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in C:\dev\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 303
   at Robust.Client.GameStates.ClientGameStateManager.PredictTicks(GameTick predictionTarget) in C:\dev\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 433
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in C:\dev\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 366
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in C:\dev\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 517
   at Robust.Client.GameController.<StartupContinue>b__50_0(Object sender, FrameEventArgs args) in C:\dev\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 182
   at Robust.Shared.Timing.GameLoop.Run() in C:\dev\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 218
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in C:\dev\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 133
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in C:\dev\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 118
   at Robust.Client.GameController.<>c__DisplayClass91_0.<Run>b__0() in C:\dev\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 85
```
![image](https://user-images.githubusercontent.com/6307265/214730720-46fa51d4-ac3c-4632-a179-72d828a772f4.png)
![image](https://user-images.githubusercontent.com/6307265/214730740-bf769db9-5597-4efb-bd20-ad3552480be6.png)
![image](https://user-images.githubusercontent.com/6307265/214730752-482d1c8c-403c-4be4-b94a-8e4d9529206f.png)

**Comment by AJCM-git** [comment]
@ShadowCommander does #13696 fix this?

**Comment by ElectroJr** [comment]
> ShadowCommander does #13696 fix this?

No this is a separate occluder tree bug
