### ISSUE TITLE
ModLoader Dispose() crashes when closing the game

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/RobustToolbox#3792]
- Start the game (in development)
- Direct connect to the server
- Close the game with the X on the window, not through Rider/VS

```
[INFO] root: Shutting down! Reason: Main window closed
[INFO] map: Deleting map 1
[DEBG] clyde.win: Terminating GLFW.
[DEBG] root: Goodbye
Unhandled exception. System.InvalidOperationException: Cannot unload non-collectible AssemblyLoadContext.
   at System.Runtime.Loader.AssemblyLoadContext.Unload()
   at Robust.Shared.ContentPack.ModLoader.Dispose() in C:\Projects\space-station-14\RobustToolbox\Robust.Shared\ContentPack\ModLoader.cs:line 363
   at Robust.Shared.IoC.DependencyCollection.Clear() in C:\Projects\space-station-14\RobustToolbox\Robust.Shared\IoC\DependencyCollection.cs:line 310
   at Robust.Client.GameController.Run(DisplayMode mode, GameControllerOptions options, Func`1 logHandlerFactory) in C:\Projects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 111
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart, IMainArgs loaderArgs, GameControllerOptions options) in C:\Projects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 64
   at Robust.Client.GameController.Start(String[] args, GameControllerOptions options, Boolean contentStart, IMainArgs loaderArgs) in C:\Projects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 42
   at Robust.Client.ContentStart.Start(String[] args) in C:\Projects\space-station-14\RobustToolbox\Robust.Client\ContentStart.cs:line 10
   at Content.Client.Program.Main(String[] args) in C:\Projects\space-station-14\Content.Client\Program.cs:line 9
```

**Comment by PJB3005** [comment]
Too slow
3fa7d25ecdeb4519a52c5c48a8b371cb9665f0aa

**Comment by DrSmugleaf** [comment]
> Too slow [3fa7d25](https://github.com/space-wizards/RobustToolbox/commit/3fa7d25ecdeb4519a52c5c48a8b371cb9665f0aa)

a
