### ISSUE TITLE
Unable to start rounds in hybrid-acz dev builds

### ISSUE THREAD

**Issue by DamionDamion** [space-wizards/RobustToolbox#4662]
When attempting to start a round in a `--hybrid-acz` build.

https://github.com/space-wizards/RobustToolbox/blob/34d02256fd94ec5647cfbcc6d90633f58721cc88/Robust.Server/Audio/AudioSystem.cs#L214

```
[INFO] ticker: Starting round!
[INFO] ticker: Added game rule  (1, Secret)
[INFO] map: Creating new map 1
[DEBG] map: Binding map 1 to entity 2
[INFO] mapsel: selecting the next map from the rotation queue
[INFO] mapsel: map queue: Box, Omega, Core, Aspid, Origin, Marathon, Packed, Saltern, Bagel, Atlas, Barratry, Cluster, Gemini, Fland, Meta
[INFO] mapsel: eligible queue: (Omega, 13), (Saltern, 7), (Atlas, 5), (Cluster, 3)
[INFO] loader: No user map found: /Maps/omega.yml
[INFO] loader: Loading Map: /Maps/omega.yml
[INFO] loader: Loading map file with a root node onto an existing map!
[INFO] map: Deleting map 1
[WARN] map: Setting map 1 root to entity 3, but entity thinks it is root node of map 0.
[DEBG] map: Setting map 1 entity to 3
[DEBG] gsplit: Started split check for  (4)
[DEBG] gsplit: Stopped split check for  (4)
[INFO] map: Creating new map 2
[DEBG] map: Binding map 2 to entity 12557
[INFO] loader: No user map found: /Maps/centcomm.yml
[INFO] loader: Loading Map: /Maps/centcomm.yml
[DEBG] gsplit: Started split check for Central Command (12558)
[DEBG] gsplit: Stopped split check for Central Command (12558)
[ERRO] ticker: Exception caught while trying to start the round! Restarting round...
[ERRO] runtime: Caught exception in "GameTicker"
Robust.Shared.GameObjects.EntityCreationException: Exception inside InitializeAndStartEntity
 ---> System.IO.FileNotFoundException: Unable to find metadata for audio file /Audio/Machines/light_tube_on.ogg
   at Robust.Server.Audio.AudioSystem.GetAudioLengthImpl(String filename) in /builds/ss14/space-station-14/RobustToolbox/Robust.Server/Audio/AudioSystem.cs:line 214
   at Robust.Shared.Audio.Systems.SharedAudioSystem.GetAudioLength(String filename) in /builds/ss14/space-station-14/RobustToolbox/Robust.Shared/Audio/Systems/SharedAudioSystem.cs:line 221
   at Robust.Shared.Audio.Systems.SharedAudioSystem.SetupAudio(EntityUid uid, String fileName, Nullable`1 audioParams) in /builds/ss14/space-station-14/RobustToolbox/Robust.Shared/Audio/Systems/SharedAudioSystem.cs:line 144
   at Robust.Server.Audio.AudioSystem.PlayEntity(String filename, Filter playerFilter, EntityUid uid, Boolean recordReplay, Nullable`1 audioParams) in /builds/ss14/space-station-14/RobustToolbox/Robust.Server/Audio/AudioSystem.cs:line 88
   at Robust.Shared.Audio.Systems.SharedAudioSystem.PlayEntity(SoundSpecifier sound, Filter playerFilter, EntityUid uid, Boolean recordReplay, Nullable`1 audioParams) in /builds/ss14/space-station-14/RobustToolbox/Robust.Shared/Audio/Systems/SharedAudioSystem.cs:line 338
   at Content.Server.Light.EntitySystems.PoweredLightSystem.UpdateLight(EntityUid uid, PoweredLightComponent light, ApcPowerReceiverComponent powerReceiver, AppearanceComponent appearance) in /builds/ss14/space-station-14/Content.Server/Light/EntitySystems/PoweredLightSystem.cs:line 290
   at Content.Server.Light.EntitySystems.PoweredLightSystem.OnMapInit(EntityUid uid, PoweredLightComponent light, MapInitEvent args) in /builds/ss14/space-station-14/Content.Server/Light/EntitySystems/PoweredLightSystem.cs:line 93
```

What am I missing?

Thanks,

**Comment by metalgearsloth** [comment]
Use Content.Packaging not the python script.

**Comment by DamionDamion** [comment]
Thank you, it is working now
