### ISSUE TITLE
Exception when TextEdit placeholder text spans multiple lines

### ISSUE THREAD

**Issue by 0x6273** [space-wizards/RobustToolbox#4953]
If a TextEdit placeholder spans multiple lines, it is possible to put the cursor on different lines. On release it's not possible to type except when the cursor is on the first line, and attempting to do so on debug throws this exception:

```
Unhandled exception. System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Robust.Shared.Utility.Rope.Split(Node rope, Int64 index) in /home/user/Projects/space-station-14/RobustToolbox/Robust.Shared/Utility/TextRope.cs:line 362
   at Robust.Shared.Utility.Rope.ReplaceSubstring(Node rope, Int64 start, Int64 length, String text) in /home/user/Projects/space-station-14/RobustToolbox/Robust.Shared/Utility/TextRope.cs:line 396
   at Robust.Client.UserInterface.Controls.TextEdit.InsertAtCursor(String text) in /home/user/Projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/Controls/TextEdit.cs:line 855
   at Robust.Client.UserInterface.Controls.TextEdit.TextEntered(GUITextEnteredEventArgs args) in /home/user/Projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/Controls/TextEdit.cs:line 730
   at Robust.Client.UserInterface.UserInterfaceManager.TextEntered(TextEnteredEventArgs textEnteredEvent) in /home/user/Projects/space-station-14/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.Input.cs:line 233
   at Robust.Client.GameController.TextEntered(TextEnteredEventArgs textEnteredEvent) in /home/user/Projects/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Input.cs:line 25
   at Robust.Client.Graphics.Clyde.Clyde.DispatchSingleEvent(DEventBase ev) in /home/user/Projects/space-station-14/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Events.cs:line 62
   at Robust.Client.Graphics.Clyde.Clyde.DispatchEvents() in /home/user/Projects/space-station-14/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Events.cs:line 31
   at Robust.Client.Graphics.Clyde.Clyde.ProcessInput(FrameEventArgs frameEventArgs) in /home/user/Projects/space-station-14/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Windowing.cs:line 392
   at Robust.Client.GameController.Input(FrameEventArgs frameEventArgs) in /home/user/Projects/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 489
   at Robust.Client.GameController.<StartupContinue>b__58_2(Object sender, FrameEventArgs args) in /home/user/Projects/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 240
   at Robust.Shared.Timing.GameLoop.Run() in /home/user/Projects/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 187
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/user/Projects/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 162
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/user/Projects/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 147
   at Robust.Client.GameController.<>c__DisplayClass100_0.<Run>b__0() in /home/user/Projects/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 106
```

I encountered this while developing for a downstream fork. I don't think a multi line placeholder text is present in content currently.

Repro:

- Apply following patch:
```diff
diff --git a/Resources/Locale/en-US/preferences/ui/flavor-text.ftl b/Resources/Locale/en-US/preferences/ui/flavor-text.ftl
index e7172c1528..3469f9ca47 100644
--- a/Resources/Locale/en-US/preferences/ui/flavor-text.ftl
+++ b/Resources/Locale/en-US/preferences/ui/flavor-text.ftl
@@ -1 +1,3 @@
-flavor-text-placeholder = An outer description of your character that others can get by looking at them...
+flavor-text-placeholder = An outer description
+    of your character that others can get
+    by looking at them...
```
- `sudo cvar ic.flavor_text true`
- `golobby`
- Customize -> Description
- Click a line that's not the first line
![image](https://github.com/space-wizards/RobustToolbox/assets/48867431/5e0e6a7c-f0b6-48be-9247-cf27a4e9035a)
- Type any character
- Client crashes with the above exception

**Comment by 0x6273** [comment]
It looks like there is code that's supposed to clamp `CursorPosition` here:
https://github.com/space-wizards/RobustToolbox/blob/c12971cb9bc3b58de831e3418b4d06874620cc0b/Robust.Client/UserInterface/Controls/TextEdit.cs#L120-L122

But it looks like it never actually gets clamped because the code that handles clicking and arrow keys sets the field directly, bypassing the property setter.
