### ISSUE TITLE
Starting server with empty config file causes crash.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#51]
```
System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=There is an error in XML document (0, 0).
  Source=System.Xml
  StackTrace:
       at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
       at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
       at SS14.Server.Services.Configuration.ConfigurationManager.Initialize(String ConfigFileLoc) in C:\Users\Simon\Documents\SS13 Repos\space-station-14\SS14.Server.Services\Configuration\ConfigurationManager.cs:line 25
       at SS14.Server.SS14Server..ctor() in C:\Users\Simon\Documents\SS13 Repos\space-station-14\SS14.Server\SS14Server.cs:line 100
       at SS14.Server.EntryPoint.Main(String[] args) in C:\Users\Simon\Documents\SS13 Repos\space-station-14\SS14.Server\Program.cs:line 24
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146232000
       LineNumber=0
       LinePosition=0
       Message=Root element is missing.
       Source=System.Xml
       SourceUri=""
       StackTrace:
            at System.Xml.XmlTextReaderImpl.Throw(Exception e)
            at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
            at System.Xml.XmlTextReaderImpl.Read()
            at System.Xml.XmlTextReader.Read()
            at System.Xml.XmlReader.MoveToContent()
            at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPersistentConfiguration.Read6_PersistentConfiguration()
       InnerException: 
```

Piss easy fix but still I'm gonna report it.

**Comment by YotaXP** [comment]
Literally sneezing will cause a crash at this point in the game, as you're probably going to accidentally click something.

**Comment by CorruptComputer** [comment]
You could make it generate a new config file if its empty

**Comment by xecollons** [comment]
Or handle the exception without allowing the server to launch.

**Comment by PJB3005** [comment]
Nah just don't load a config if the config parsing fails.

**Comment by ZoldorfTheWizard** [comment]
a... aaa... ACHOO

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotImplementedException: The method or operation is not implemented.
   at ......
```

**Comment by PJB3005** [comment]
Honestly until interaction is implemented we should just remove that crash because it's so fucking annoying.

**Comment by Andrew-Fall** [comment]
Ah so that is why it crashes? I thought it was just that unstable or something. Good to know.

**Comment by ZoldorfTheWizard** [comment]
#66
