### ISSUE TITLE
Metrics listener excepts with "Broken pipe" on startup almost every time. Even though metrics are still fine

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/RobustToolbox#5260]
Not sure exactly why it happens. But it pretty much always happens on startup. And it seems to be harmless, since metrics work anyway.

```
[ERRO] metrics.server: Exception in metrics listener
SpaceWizards.HttpListener.HttpListenerException (0x80131620): Unable to write data to the transport connection: Broken pipe.
   at SpaceWizards.HttpListener.HttpResponseStream.EndWriteCore(IAsyncResult asyncResult)
   at SpaceWizards.HttpListener.HttpResponseStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__62_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
 --- End of stack trace from previous location ---
   at System.IO.Compression.DeflateStream.WriteDeflaterOutputAsync(CancellationToken cancellationToken)
   at System.IO.Compression.DeflateStream.<WriteAsyncMemory>g__Core|66_0(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.IO.BufferedStream.WriteToUnderlyingStreamAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken, Task semaphoreLockTask)
   at Prometheus.TextSerializer.WriteFamilyDeclarationAsync(String name, Byte[] nameBytes, Byte[] helpBytes, MetricType type, Byte[] typeBytes, CancellationToken cancel)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Prometheus.Collector`1.CollectAndSerializeAsync(IMetricsSerializer serializer, Boolean writeFamilyDeclaration, CancellationToken cancel)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Prometheus.CollectorFamily.CollectAndSerialize(Collector collector, SerializeFamilyOperation operation, CancellationToken cancel)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Prometheus.CollectorFamily.ForEachCollectorAsync[TArg](Func`4 func, TArg arg, CancellationToken cancel)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Prometheus.CollectorFamily.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Prometheus.CollectorRegistry.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
   at Robust.Server.DataMetrics.MetricsManager.ManagedHttpListenerMetricsServer.<>c__DisplayClass6_1.<<ListenerThread>b__0>d.MoveNext() in /home/runner/work/axolotl-mrp-14/axolotl-mrp-14/RobustToolbox/Robust.Server/DataMetrics/MetricsManager.MetricsServer.cs:line 77
```

**Comment by madeline-celeste** [comment]
whys this marked as not required its an Error

**Comment by VasilisThePikachu** [comment]
> whys this marked as not required its an Error

Maybe it was too low rated i will admit but It does not really hurt the game though, it comes up on startup and the function behind it still works perfectly.
