### ISSUE TITLE
Client randomly crashes in SharedUserInterfaceSystem.Update

### ISSUE THREAD

**Issue by stalengd** [space-wizards/RobustToolbox#5309]
Client crashes with the following exeption:

```
Unhandled exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Robust.Shared.GameObjects.SharedUserInterfaceSystem.Update(Single frameTime) in E:\Projects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedUserInterfaceSystem.cs:line 951
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in E:\Projects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 306
   at Robust.Client.GameStates.ClientGameStateManager.PredictTicks(GameTick predictionTarget) in E:\Projects\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 521
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in E:\Projects\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 454
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in E:\Projects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 535
   at Robust.Client.GameController.<StartupContinue>b__58_0(Object sender, FrameEventArgs args) in E:\Projects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 224
   at Robust.Shared.Timing.GameLoop.Run() in E:\Projects\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 240
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in E:\Projects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 162
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in E:\Projects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 147
   at Robust.Client.GameController.<>c__DisplayClass100_0.<Run>b__0() in E:\Projects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 106
```

Apparently, the reason is that a `_parallel.ProcessNow()` call for some reason may return control before all jobs is processed. at least I was able to confirm this with the help of logs:

![image](https://github.com/user-attachments/assets/3bb03beb-631b-4104-9f46-43a8fcc6c493)

Possible way to reproduce:
1. Open at least 3 user interfaces from entities so game should check distance to them in update
2. Wait from several minutes to hour, its really random

**Comment by stalengd** [comment]
Should be fixed with https://github.com/space-wizards/RobustToolbox/pull/5311
