### ISSUE TITLE
rmgrid console command causes client crash

### ISSUE THREAD

**Issue by Moneyl** [space-wizards/RobustToolbox#981]
Steps to reproduce:
1. Find a grid id my mousing over the station with the F3 overlay.
2. Delete that grid with `rmgrid` in the console. `rmgrid 2` for example. The client should hit an exception then crash.
3. If the grid you try to delete doesn't exist nothing will happen, so double check you're deleting a valid grid id.

```cs
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '1' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Shared.Map.MapManager.GetDefaultGrid(MapId mapID) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Shared\Map\MapManager.cs:line 392
   at Robust.Shared.Map.MapManager.FindGridAt(MapId mapId, Vector2 worldPos) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Shared\Map\MapManager.cs:line 524
   at Robust.Client.Graphics.ClientEye.EyeManager.ScreenToWorld(Vector2 point) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Client\Graphics\ClientEye\EyeManager.cs:line 94
   at Robust.Client.Graphics.ClientEye.EyeManager.ScreenToWorld(ScreenCoordinates point) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Client\Graphics\ClientEye\EyeManager.cs:line 83
   at Content.Client.State.GameScreen.FrameUpdate(FrameEventArgs e) in C:\Users\moneyl\source\repos\space-station-14\Content.Client\State\GameScreen.cs:line 66
   at Robust.Client.State.StateManager.FrameUpdate(FrameEventArgs e) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Client\State\StateManager.cs:line 25
   at Robust.Client.GameController._frameProcessMain(FrameEventArgs frameEventArgs) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Client\GameController.cs:line 268
   at Robust.Client.GameController.<MainLoop>b__56_3(Object sender, FrameEventArgs args) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 105
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 222
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 110
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 56
   at Robust.Client.GameController.Start(String[] args) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 37
   at Robust.Client.ContentStart.Start(String[] args) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Client\ContentStart.cs:line 10
   at Content.Client.Program.Main(String[] args) in C:\Users\moneyl\source\repos\space-station-14\Content.Client\Program.cs:line 9```

**Comment by PJB3005** [comment]
Fixed by 48ca01ab4a005abdfb690e544a46b2da052bb021
